Initial implementation
bitrise-steplib/steps-cordova-prepare pull request #1
Opened 2018-03-22 15:47 UTC by kdobmayer

2018-03-22 15:53 UTC, trapacska requested changes

2018-03-22 15:53 UTC, trapacska commented on main.go
> +	log.Infof("$ %s %s", name, strings.Join(arg, " "))
please do not use logging outside of main()

2018-03-22 15:53 UTC, trapacska commented on main.go
> +	cmd := exec.Command(name, arg...)
we have `command.NewWithXyz` call so you can skip setting STDs, also you can just simply return with that.
And if you function is one liner, do you need the function separated?

2018-03-22 15:53 UTC, trapacska commented on main.go
> +func update(version string) error {
```
if version == "latest" {
return runCommand("npm", "install", "-g", "cordova")
}else{
return runCommand("npm", "install", "-g", "cordova@"+version)
}
```

2018-03-22 15:53 UTC, trapacska commented on main.go
> +	if err := os.Chdir(cfg.WorkDir); err != nil {
avoid using os.Chdir. Set the workDir for the command itself please

2018-03-23 11:25 UTC, trapacska approved these changes

2018-04-06 09:42 UTC, godrei approved these changes

2018-04-06 10:57 UTC, merged